FROM gradle:4.3-jdk8 as debug

WORKDIR /workspace/app

COPY . .

FROM debug as develop

USER root
RUN chown -R gradle /workspace/app
USER gradle

RUN gradle wrapper assemble \
&& cd build/libs \
&& jar -xf learner-record.jar

CMD java -jar /workspace/app/build/libs/learner-record.jar

FROM openjdk:8-jre-alpine as production

ARG JAR_DIR=/workspace/app/build/libs

COPY --from=build ${JAR_DIR}/BOOT-INF/lib /data/lib
COPY --from=build ${JAR_DIR}/META-INF /data/META-INF
COPY --from=build ${JAR_DIR}/BOOT-INF/classes /data
COPY --from=build ${JAR_DIR}/learner-record.jar /data/app.jar

# Add AppInsights config and agent jar
ADD lib/AI-Agent.xml /opt/appinsights/AI-Agent.xml
ADD https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.0.3/applicationinsights-agent-3.0.3.jar /opt/appinsights/applicationinsights-agent-3.0.3.jar

CMD java -javaagent:/opt/appinsights/applicationinsights-agent-3.0.3.jar -jar /data/app.jar
