version: "3.4"

services:

  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    restart: always

  nimbus:
    image: storm:1.2
    container_name: nimbus
    command: storm nimbus -c storm.local.hostname=localhost
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627

  drpc:
    image: storm:1.2
    container_name: drpc
    command: storm drpc -c storm.local.hostname=localhost
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 3772:3772
      - 3773:3773
      - 3774:3774

  supervisor:
    image: storm:1.2
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always
