
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  resources:
    add-mappings: false
  security:
    user:
      name: ${AUTH_USER:user}
      password: ${AUTH_PASSWORD:password}

server:
  port: 9000

xapi:
  username: ${XAPI_USERNAME:66f2b4fc001e3da992d23b57d8a7457655bea078}
  password: ${XAPI_PASSWORD:1c0e1b6827606d7efed71e204939d048f94f842b}
  url: ${XAPI_URL:http://test-xapi.cshr.digital/data/xAPI}