spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
  resources:
    add-mappings: false
  flyway:
    locations: classpath:db/migration/{vendor}
  jpa:
    hibernate:
      ddl-auto: none
  cache:
    cache-names: courseId
    caffeine:
      spec: maximumSize=500, expireAfterAccess=1h
  data:
    mongodb:
      uri: ${COSMOS_CONNECTION_STRING:mongodb://localhost:27017}
      database: ${DATABASE:learninglocker}
      socketTimeoutInMilliseconds: ${SOCKET_TIMEOUT_IN_MILLISECONDS:60000}
      connectionTimeoutInMilliseconds: ${CONNECTION_TIMEOUT_IN_MILLISECONDS:30000}
      maxConnectionIdleTimeInMilliseconds: ${MAX_CONNECTION_IDLE_TIME_IN_MILLISECONDS:30000}

server:
  port: 9000

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    com.zaxxer.hikari: ERROR

notifications:
  service: ${NOTIFICATION_SERVICE_URL:http://localhost:9006}
  email: ${notifications.service}/notifications/email/

xapi:
  username: ${XAPI_USERNAME:66f2b4fc001e3da992d23b57d8a7457655bea078}
  password: ${XAPI_PASSWORD:1c0e1b6827606d7efed71e204939d048f94f842b}
  url: ${XAPI_URL:http://localhost:8083/data/xAPI}

oauth:
  serviceUrl: ${OAUTH_SERVICE_URL:http://localhost:8080}
  clientId: ${CLIENT_ID:9fbd4ae2-2db3-44c7-9544-88e80255b56e}
  clientSecret: ${CLIENT_SECRET:test}
  checkTokenUrl: "${oauth.serviceUrl}/oauth/check_token"
  tokenUrl: "${oauth.serviceUrl}/oauth/token"
  maxTotalConnections: 120
  defaultMaxConnectionsPerRoute: 60
  maxPerServiceUrl: 60
  jwtKey: ${jwt_key}

identity:
  listAllUrl: "${oauth.serviceUrl}/api/identities"
  identityAPIUrl: "${oauth.serviceUrl}/api/identities"

registry:
  serviceUrl: ${REGISTRY_SERVICE_URL:http://localhost:9002}
  getCurrentUrl: "${registry.serviceUrl}/civilServants/me"
  findByUidUrlFormat: "${registry.serviceUrl}/civilServants/search/findByIdentity?uid=%s&projection=allCivilServantDetails"
  getResourceByUidUrl: "${registry.serviceUrl}/civilServants/resource/%s"
  getResourceByOrgCodeUrl: "${registry.serviceUrl}/civilServants/organisation/%s"

catalogue:
  serviceUrl: ${LEARNING_CATALOGUE_SERVICE_URL:http://localhost:9001}
  courseUrlFormat: "${catalogue.serviceUrl}/courses/%s"
  requiredLearningUrlFormat: "${catalogue.serviceUrl}/courses?mandatory=true&department=%s"
  requiredLearningUrlByDaysFormat: "${catalogue.serviceUrl}/courses?mandatory=true&days=%s"

govNotify:
  key: ${GOV_NOTIFY_API_KEY:key}
  template:
    requiredLearningDue: ${GOV_NOTIFY_REQUIRED_LEARNING_DUE_TEMPLATE_ID:template}
    completedLearning: ${GOV_NOTIFY_LEARNING_COMPLETED_TEMPLATE_ID:3f50f0eb-4c47-4e37-8a44-1628faa41924}
    inviteLearner: ${GOV_NOTIFY_INVITE_LEARNER_TEMPLATE_ID:cf623c5b-b9e9-4899-b419-4f851e581056}
    cancelBooking: ${GOV_NOTIFY_CANCEL_BOOKING_TEMPLATE_ID:cc525c34-1a31-4fa1-ab19-862fd223caab}
    cancelEvent: ${GOV_NOTIFY_CANCEL_EVENT_TEMPLATE_ID:26e0e8ae-7617-40f7-be37-ca63b8a0d257}
    bookingConfirmed: ${GOV_NOTIFY_BOOKING_CONFIRMED:8efb52bd-9ada-402e-8fab-84a751bf4a71}
    bookingConfirmedLineManager: ${GOV_NOTIFY_BOOKING_CONFIRMED_LINE_MANAGER:5e3a76c5-5178-4c8c-9bcd-87886dc0efef}
    bookingRequestLineManager: ${GOV_NOTIFY_BOOKING_REQUEST_LINE_MANAGER:659f8f61-d326-428e-996d-f890b61a2f96}
    bookingCancelledLineManager: ${GOV_NOTIFY_BOOKING_CANCELLED_LINE_MANAGER:c00fac77-8448-41c9-b15c-23361ccef419}
    bookingRequested: ${GOV_NOTIFY_BOOKING_REQUESTED:ae678ea1-ae7a-42f3-aa27-037336b346c4}

lpg-ui:
  serviceUrl: ${LPG_UI_URL:http://localhost:3001}
  bookingUrlFormat: "${lpg-ui.serviceUrl}/book/%s/%s/choose-date"

csl.homepage: "https://cslearning.gov.uk/"

retention:
  timeInMonths: ${RETENTION_TIME_IN_MONTHS:36}

---

spring:
  profiles: production
  datasource:
    url: ${DATASOURCE:jdbc:mysql://localhost:3306/learner_record?user=root&password=password&useSSL=false}
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
