
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  resources:
    add-mappings: false

server:
  port: 9000

xapi:
  username: ${XAPI_USERNAME:66f2b4fc001e3da992d23b57d8a7457655bea078}
  password: ${XAPI_PASSWORD:1c0e1b6827606d7efed71e204939d048f94f842b}
  url: ${XAPI_URL:http://localhost:8083/data/xAPI}

oauth:
  serviceUrl: ${OAUTH_SERVICE_URL:http://localhost:8080}
  clientId: ${CLIENT_ID:9fbd4ae2-2db3-44c7-9544-88e80255b56e}
  clientSecret: ${CLIENT_SECRET:test}
  checkTokenUrl: "${oauth.serviceUrl}/oauth/check_token"
  tokenUrl: "${oauth.serviceUrl}/oauth/token"

identity:
  listAllUrl: "${oauth.serviceUrl}/api/identities"

registry:
  serviceUrl: ${REGISTRY_SERVICE_URL:http://localhost:9002}
  getCurrentUrl: "${registry.serviceUrl}/civilServants/me"
  findByUidUrlFormat: "${registry.serviceUrl}/civilServants/search/findByIdentity?uid=%s&projection=allCivilServantDetails"

catalogue:
  username: ${LEARNING_CATALOGUE_USERNAME:user}
  password: ${LEARNING_CATALOGUE_PASSWORD:password}
  serviceUrl: ${LEARNING_CATALOGUE_SERVICE_URL:http://localhost:9001}
  courseUrlFormat: "${catalogue.serviceUrl}/courses/%s"
  requiredLearningUrlFormat: "${catalogue.serviceUrl}/courses?mandatory=true&department=%s"

govNotify:
  key: ${GOV_NOTIFY_API_KEY:key}
  template:
    requiredLearningDue: ${GOV_NOTIFY_REQUIRED_LEARNING_DUE_TEMPLATE_ID:template}
    completedLearning: ${GOV_NOTIFY_LEARNING_COMPLETED_TEMPLATE_ID:template}