#! /usr/bin/env bash

docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
docker pull cshr/lpg-learner-record || true
./gradlew init
./gradlew build
docker build -t cshr/lpg-learner-record:latest .
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
docker tag cshr/lpg-learner-record:latest cshr/lpg-learner-record:${TRAVIS_COMMIT}
docker push cshr/lpg-learner-record

./environ/deploy dev ${TRAVIS_COMMIT}

# cd test/headless
# npm install
